/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as DashboardLayoutIndexRouteImport } from './routes/_dashboardLayout/index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as DashboardLayoutTableConverterRouteImport } from './routes/_dashboardLayout/table-converter'
import { Route as DashboardLayoutFilesRouteImport } from './routes/_dashboardLayout/files'
import { Route as DashboardLayoutDataTableRouteImport } from './routes/_dashboardLayout/data-table'
import { Route as DashboardLayoutDashboardRouteImport } from './routes/_dashboardLayout/dashboard'
import { Route as DashboardLayoutSplatRouteImport } from './routes/_dashboardLayout/$'
import { Route as DemoApiNamesRouteImport } from './routes/demo.api.names'
import { Route as ApiDownloadFileNameRouteImport } from './routes/api.download.$fileName'
import { Route as DashboardLayoutDemoServerFuncsRouteImport } from './routes/_dashboardLayout/demo.server-funcs'
import { Route as DashboardLayoutDemoApiRequestRouteImport } from './routes/_dashboardLayout/demo.api-request'
import { Route as DashboardLayoutDemoSsrIndexRouteImport } from './routes/_dashboardLayout/demo.ssr.index'
import { Route as DashboardLayoutDemoSsrSpaModeRouteImport } from './routes/_dashboardLayout/demo.ssr.spa-mode'
import { Route as DashboardLayoutDemoSsrFullSsrRouteImport } from './routes/_dashboardLayout/demo.ssr.full-ssr'
import { Route as DashboardLayoutDemoSsrDataOnlyRouteImport } from './routes/_dashboardLayout/demo.ssr.data-only'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutTableConverterRoute =
  DashboardLayoutTableConverterRouteImport.update({
    id: '/table-converter',
    path: '/table-converter',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutFilesRoute = DashboardLayoutFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const DashboardLayoutDataTableRoute =
  DashboardLayoutDataTableRouteImport.update({
    id: '/data-table',
    path: '/data-table',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDashboardRoute =
  DashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutSplatRoute = DashboardLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadFileNameRoute = ApiDownloadFileNameRouteImport.update({
  id: '/api/download/$fileName',
  path: '/api/download/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutDemoServerFuncsRoute =
  DashboardLayoutDemoServerFuncsRouteImport.update({
    id: '/demo/server-funcs',
    path: '/demo/server-funcs',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDemoApiRequestRoute =
  DashboardLayoutDemoApiRequestRouteImport.update({
    id: '/demo/api-request',
    path: '/demo/api-request',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDemoSsrIndexRoute =
  DashboardLayoutDemoSsrIndexRouteImport.update({
    id: '/demo/ssr/',
    path: '/demo/ssr/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDemoSsrSpaModeRoute =
  DashboardLayoutDemoSsrSpaModeRouteImport.update({
    id: '/demo/ssr/spa-mode',
    path: '/demo/ssr/spa-mode',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDemoSsrFullSsrRoute =
  DashboardLayoutDemoSsrFullSsrRouteImport.update({
    id: '/demo/ssr/full-ssr',
    path: '/demo/ssr/full-ssr',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutDemoSsrDataOnlyRoute =
  DashboardLayoutDemoSsrDataOnlyRouteImport.update({
    id: '/demo/ssr/data-only',
    path: '/demo/ssr/data-only',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$': typeof DashboardLayoutSplatRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/data-table': typeof DashboardLayoutDataTableRoute
  '/files': typeof DashboardLayoutFilesRoute
  '/table-converter': typeof DashboardLayoutTableConverterRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof DashboardLayoutIndexRoute
  '/demo/api-request': typeof DashboardLayoutDemoApiRequestRoute
  '/demo/server-funcs': typeof DashboardLayoutDemoServerFuncsRoute
  '/api/download/$fileName': typeof ApiDownloadFileNameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/ssr/data-only': typeof DashboardLayoutDemoSsrDataOnlyRoute
  '/demo/ssr/full-ssr': typeof DashboardLayoutDemoSsrFullSsrRoute
  '/demo/ssr/spa-mode': typeof DashboardLayoutDemoSsrSpaModeRoute
  '/demo/ssr': typeof DashboardLayoutDemoSsrIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof DashboardLayoutSplatRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/data-table': typeof DashboardLayoutDataTableRoute
  '/files': typeof DashboardLayoutFilesRoute
  '/table-converter': typeof DashboardLayoutTableConverterRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof DashboardLayoutIndexRoute
  '/demo/api-request': typeof DashboardLayoutDemoApiRequestRoute
  '/demo/server-funcs': typeof DashboardLayoutDemoServerFuncsRoute
  '/api/download/$fileName': typeof ApiDownloadFileNameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/ssr/data-only': typeof DashboardLayoutDemoSsrDataOnlyRoute
  '/demo/ssr/full-ssr': typeof DashboardLayoutDemoSsrFullSsrRoute
  '/demo/ssr/spa-mode': typeof DashboardLayoutDemoSsrSpaModeRoute
  '/demo/ssr': typeof DashboardLayoutDemoSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboardLayout/$': typeof DashboardLayoutSplatRoute
  '/_dashboardLayout/dashboard': typeof DashboardLayoutDashboardRoute
  '/_dashboardLayout/data-table': typeof DashboardLayoutDataTableRoute
  '/_dashboardLayout/files': typeof DashboardLayoutFilesRoute
  '/_dashboardLayout/table-converter': typeof DashboardLayoutTableConverterRoute
  '/api/upload': typeof ApiUploadRoute
  '/_dashboardLayout/': typeof DashboardLayoutIndexRoute
  '/_dashboardLayout/demo/api-request': typeof DashboardLayoutDemoApiRequestRoute
  '/_dashboardLayout/demo/server-funcs': typeof DashboardLayoutDemoServerFuncsRoute
  '/api/download/$fileName': typeof ApiDownloadFileNameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/_dashboardLayout/demo/ssr/data-only': typeof DashboardLayoutDemoSsrDataOnlyRoute
  '/_dashboardLayout/demo/ssr/full-ssr': typeof DashboardLayoutDemoSsrFullSsrRoute
  '/_dashboardLayout/demo/ssr/spa-mode': typeof DashboardLayoutDemoSsrSpaModeRoute
  '/_dashboardLayout/demo/ssr/': typeof DashboardLayoutDemoSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$'
    | '/dashboard'
    | '/data-table'
    | '/files'
    | '/table-converter'
    | '/api/upload'
    | '/'
    | '/demo/api-request'
    | '/demo/server-funcs'
    | '/api/download/$fileName'
    | '/demo/api/names'
    | '/demo/ssr/data-only'
    | '/demo/ssr/full-ssr'
    | '/demo/ssr/spa-mode'
    | '/demo/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/dashboard'
    | '/data-table'
    | '/files'
    | '/table-converter'
    | '/api/upload'
    | '/'
    | '/demo/api-request'
    | '/demo/server-funcs'
    | '/api/download/$fileName'
    | '/demo/api/names'
    | '/demo/ssr/data-only'
    | '/demo/ssr/full-ssr'
    | '/demo/ssr/spa-mode'
    | '/demo/ssr'
  id:
    | '__root__'
    | '/_dashboardLayout'
    | '/login'
    | '/_dashboardLayout/$'
    | '/_dashboardLayout/dashboard'
    | '/_dashboardLayout/data-table'
    | '/_dashboardLayout/files'
    | '/_dashboardLayout/table-converter'
    | '/api/upload'
    | '/_dashboardLayout/'
    | '/_dashboardLayout/demo/api-request'
    | '/_dashboardLayout/demo/server-funcs'
    | '/api/download/$fileName'
    | '/demo/api/names'
    | '/_dashboardLayout/demo/ssr/data-only'
    | '/_dashboardLayout/demo/ssr/full-ssr'
    | '/_dashboardLayout/demo/ssr/spa-mode'
    | '/_dashboardLayout/demo/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiDownloadFileNameRoute: typeof ApiDownloadFileNameRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/': {
      id: '/_dashboardLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/table-converter': {
      id: '/_dashboardLayout/table-converter'
      path: '/table-converter'
      fullPath: '/table-converter'
      preLoaderRoute: typeof DashboardLayoutTableConverterRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/files': {
      id: '/_dashboardLayout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof DashboardLayoutFilesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/data-table': {
      id: '/_dashboardLayout/data-table'
      path: '/data-table'
      fullPath: '/data-table'
      preLoaderRoute: typeof DashboardLayoutDataTableRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/$': {
      id: '/_dashboardLayout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DashboardLayoutSplatRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$fileName': {
      id: '/api/download/$fileName'
      path: '/api/download/$fileName'
      fullPath: '/api/download/$fileName'
      preLoaderRoute: typeof ApiDownloadFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/demo/server-funcs': {
      id: '/_dashboardLayout/demo/server-funcs'
      path: '/demo/server-funcs'
      fullPath: '/demo/server-funcs'
      preLoaderRoute: typeof DashboardLayoutDemoServerFuncsRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/demo/api-request': {
      id: '/_dashboardLayout/demo/api-request'
      path: '/demo/api-request'
      fullPath: '/demo/api-request'
      preLoaderRoute: typeof DashboardLayoutDemoApiRequestRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/demo/ssr/': {
      id: '/_dashboardLayout/demo/ssr/'
      path: '/demo/ssr'
      fullPath: '/demo/ssr'
      preLoaderRoute: typeof DashboardLayoutDemoSsrIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/demo/ssr/spa-mode': {
      id: '/_dashboardLayout/demo/ssr/spa-mode'
      path: '/demo/ssr/spa-mode'
      fullPath: '/demo/ssr/spa-mode'
      preLoaderRoute: typeof DashboardLayoutDemoSsrSpaModeRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/demo/ssr/full-ssr': {
      id: '/_dashboardLayout/demo/ssr/full-ssr'
      path: '/demo/ssr/full-ssr'
      fullPath: '/demo/ssr/full-ssr'
      preLoaderRoute: typeof DashboardLayoutDemoSsrFullSsrRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/demo/ssr/data-only': {
      id: '/_dashboardLayout/demo/ssr/data-only'
      path: '/demo/ssr/data-only'
      fullPath: '/demo/ssr/data-only'
      preLoaderRoute: typeof DashboardLayoutDemoSsrDataOnlyRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
  }
}

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutSplatRoute: typeof DashboardLayoutSplatRoute
  DashboardLayoutDashboardRoute: typeof DashboardLayoutDashboardRoute
  DashboardLayoutDataTableRoute: typeof DashboardLayoutDataTableRoute
  DashboardLayoutFilesRoute: typeof DashboardLayoutFilesRoute
  DashboardLayoutTableConverterRoute: typeof DashboardLayoutTableConverterRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutDemoApiRequestRoute: typeof DashboardLayoutDemoApiRequestRoute
  DashboardLayoutDemoServerFuncsRoute: typeof DashboardLayoutDemoServerFuncsRoute
  DashboardLayoutDemoSsrDataOnlyRoute: typeof DashboardLayoutDemoSsrDataOnlyRoute
  DashboardLayoutDemoSsrFullSsrRoute: typeof DashboardLayoutDemoSsrFullSsrRoute
  DashboardLayoutDemoSsrSpaModeRoute: typeof DashboardLayoutDemoSsrSpaModeRoute
  DashboardLayoutDemoSsrIndexRoute: typeof DashboardLayoutDemoSsrIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutSplatRoute: DashboardLayoutSplatRoute,
  DashboardLayoutDashboardRoute: DashboardLayoutDashboardRoute,
  DashboardLayoutDataTableRoute: DashboardLayoutDataTableRoute,
  DashboardLayoutFilesRoute: DashboardLayoutFilesRoute,
  DashboardLayoutTableConverterRoute: DashboardLayoutTableConverterRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutDemoApiRequestRoute: DashboardLayoutDemoApiRequestRoute,
  DashboardLayoutDemoServerFuncsRoute: DashboardLayoutDemoServerFuncsRoute,
  DashboardLayoutDemoSsrDataOnlyRoute: DashboardLayoutDemoSsrDataOnlyRoute,
  DashboardLayoutDemoSsrFullSsrRoute: DashboardLayoutDemoSsrFullSsrRoute,
  DashboardLayoutDemoSsrSpaModeRoute: DashboardLayoutDemoSsrSpaModeRoute,
  DashboardLayoutDemoSsrIndexRoute: DashboardLayoutDemoSsrIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiDownloadFileNameRoute: ApiDownloadFileNameRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
